/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.panel;

import javax.swing.JLabel;

/**
 *
 * @author ADVAN
 */

public class PanelIdle extends javax.swing.JPanel {

    public PanelIdle() {
            initComponents();

            // TEXT
            lblInfo.setText("Tempelkan kartu RFID Anda");

            // CENTER
            lblJam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            lblTanggal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            lblInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

            // LOADING ANIMATION
            loading.setIndeterminate(true);

            // ICON
            jLabel1.setText("🔄");
            jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 40));
            jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

            // START JAM
            startClock();
        }

    
    private void startClock() {
    new javax.swing.Timer(1000, e -> {
        java.time.LocalDateTime now = java.time.LocalDateTime.now();

        lblJam.setText(now.format(
            java.time.format.DateTimeFormatter.ofPattern("HH:mm:ss")
        ));

        lblTanggal.setText(now.format(
            java.time.format.DateTimeFormatter.ofPattern("EEEE, dd MMMM yyyy")
        ));
    }).start();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPanel = new javax.swing.JPanel();
        lblJam = new javax.swing.JLabel();
        lblTanggal = new javax.swing.JLabel();
        lblInfo = new javax.swing.JLabel();
        loading = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();

        lblJam.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblJam.setText("00:00");

        lblTanggal.setText("Tanggal");

        lblInfo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblInfo.setText("jLabel1");
        lblInfo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel1.setText("icon loading");

        javax.swing.GroupLayout bgPanelLayout = new javax.swing.GroupLayout(bgPanel);
        bgPanel.setLayout(bgPanelLayout);
        bgPanelLayout.setHorizontalGroup(
            bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgPanelLayout.createSequentialGroup()
                .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgPanelLayout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblJam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTanggal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(bgPanelLayout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(loading, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgPanelLayout.createSequentialGroup()
                        .addGap(283, 283, 283)
                        .addComponent(jLabel1)))
                .addContainerGap(193, Short.MAX_VALUE))
        );
        bgPanelLayout.setVerticalGroup(
            bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgPanelLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(lblJam)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTanggal)
                .addGap(31, 31, 31)
                .addComponent(lblInfo)
                .addGap(100, 100, 100)
                .addComponent(loading, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblJam;
    private javax.swing.JLabel lblTanggal;
    private javax.swing.JProgressBar loading;
    // End of variables declaration//GEN-END:variables
}
